/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheetRouteImport } from './routes/sheet'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LdcpRouteImport } from './routes/ldcp'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SheetRoute = SheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LdcpRoute = LdcpRouteImport.update({
  id: '/ldcp',
  path: '/ldcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ldcp': typeof LdcpRoute
  '/portfolio': typeof PortfolioRoute
  '/sheet': typeof SheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ldcp': typeof LdcpRoute
  '/portfolio': typeof PortfolioRoute
  '/sheet': typeof SheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ldcp': typeof LdcpRoute
  '/portfolio': typeof PortfolioRoute
  '/sheet': typeof SheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/ldcp' | '/portfolio' | '/sheet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/ldcp' | '/portfolio' | '/sheet'
  id: '__root__' | '/' | '/analytics' | '/ldcp' | '/portfolio' | '/sheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LdcpRoute: typeof LdcpRoute
  PortfolioRoute: typeof PortfolioRoute
  SheetRoute: typeof SheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheet': {
      id: '/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof SheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ldcp': {
      id: '/ldcp'
      path: '/ldcp'
      fullPath: '/ldcp'
      preLoaderRoute: typeof LdcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LdcpRoute: LdcpRoute,
  PortfolioRoute: PortfolioRoute,
  SheetRoute: SheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
