/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPsxPricesRouteImport } from './routes/api/public/psx-prices'
import { Route as ApiPublicKse100RouteImport } from './routes/api/public/kse100'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPsxPricesRoute = ApiPublicPsxPricesRouteImport.update({
  id: '/api/public/psx-prices',
  path: '/api/public/psx-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKse100Route = ApiPublicKse100RouteImport.update({
  id: '/api/public/kse100',
  path: '/api/public/kse100',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/portfolio': typeof PortfolioRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/kse100': typeof ApiPublicKse100Route
  '/api/public/psx-prices': typeof ApiPublicPsxPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/portfolio': typeof PortfolioRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/kse100': typeof ApiPublicKse100Route
  '/api/public/psx-prices': typeof ApiPublicPsxPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/portfolio': typeof PortfolioRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/kse100': typeof ApiPublicKse100Route
  '/api/public/psx-prices': typeof ApiPublicPsxPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/portfolio'
    | '/welcome'
    | '/api/public/kse100'
    | '/api/public/psx-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/portfolio'
    | '/welcome'
    | '/api/public/kse100'
    | '/api/public/psx-prices'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/portfolio'
    | '/welcome'
    | '/api/public/kse100'
    | '/api/public/psx-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  PortfolioRoute: typeof PortfolioRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicKse100Route: typeof ApiPublicKse100Route
  ApiPublicPsxPricesRoute: typeof ApiPublicPsxPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/psx-prices': {
      id: '/api/public/psx-prices'
      path: '/api/public/psx-prices'
      fullPath: '/api/public/psx-prices'
      preLoaderRoute: typeof ApiPublicPsxPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kse100': {
      id: '/api/public/kse100'
      path: '/api/public/kse100'
      fullPath: '/api/public/kse100'
      preLoaderRoute: typeof ApiPublicKse100RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  PortfolioRoute: PortfolioRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicKse100Route: ApiPublicKse100Route,
  ApiPublicPsxPricesRoute: ApiPublicPsxPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
